# Generated by Django 6.0.3 on 2026-03-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debug', models.BooleanField(default=True)),
                ('allowed_hosts', models.CharField(blank=True, default='', help_text='Hosts permitidos (texto simple para demo).', max_length=255)),
                ('version_app', models.CharField(default='1.0.0', max_length=32)),
            ],
            options={
                'verbose_name': 'Configuración de la aplicación',
                'verbose_name_plural': 'Configuración de la aplicación',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['-creado_en'],
            },
        ),
    ]
